#请在启动参数中加入--spring.profiles.active=mysql以激活本配置文件
database: mysql

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
#    url : "jdbc:mysql://localhost:3306/bookstore"
    username: "root"
    password: "mysql"
    initialization-mode: always
